#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
//! C1 — Full-domain RFC 8785 verification of the existing RI-RS JCS surface.
//!
//! Scope is intentionally limited to canonicalization capability. This test
//! does not integrate JCS into production, does not implement ENT-007, and
//! does not exercise RI-PY.
//!
//! Evidence sources:
//! - RFC 8785 §3.2.2–§3.2.4 primitive/string/number/sorting/UTF-8 examples
//! - RFC 8785 Appendix B number serialization samples
//! - RFC 8785 §3.1 I-JSON duplicate-property precondition
//!
//! The canonical byte expectations in this file are independent of the Rust
//! JCS engine: they are frozen from the RFC examples rather than generated by
//! `jcs::canonical_bytes`.

mod jcs;

use serde_json::Value;

fn canonical(input: &str) -> Vec<u8> {
    let value: Value = serde_json::from_str(input).expect("C1 input must be valid JSON");
    jcs::canonical_bytes(&value).expect("JCS canonicalization must succeed")
}

#[test]
fn c1_rfc_section_3_2_2_primitive_and_string_sample() {
    let input = r#"
    {
      "numbers": [333333333.33333329, 1E30, 4.50,
                  2e-3, 0.000000000000000000000000001],
      "string": "\u20ac$\u000F\u000aA'\u0042\u0022\u005c\\\"\/",
      "literals": [null, true, false]
    }
    "#;

    // RFC 8785 §3.2.4, canonical UTF-8 byte sequence.
    let expected = hex::decode(
        "7b226c69746572616c73223a5b6e756c6c2c747275652c66616c73655d2c22\
         6e756d62657273223a5b3333333333333333332e333333333333332c31652b\
         33302c342e352c302e3030322c31652d32375d2c22737472696e67223a22e2\
         82ac245c75303030665c6e4127425c225c5c5c5c5c222f227d",
    )
    .expect("RFC hexadecimal vector must decode");

    assert_eq!(canonical(input), expected);
}

#[test]
fn c1_rfc_utf16_property_sorting_sample() {
    let input = r#"
    {
      "\u20ac": "Euro Sign",
      "\r": "Carriage Return",
      "\ufb33": "Hebrew Letter Dalet With Dagesh",
      "1": "One",
      "\ud83d\ude00": "Emoji: Grinning Face",
      "\u0080": "Control",
      "\u00f6": "Latin Small Letter O With Diaeresis"
    }
    "#;

    // RFC 8785 §3.2.3 ordering is UTF-16-code-unit based; serialization then
    // emits non-control Unicode characters as their UTF-8 code points.
    let expected = concat!(
        "{\"\\r\":\"Carriage Return\",\"1\":\"One\",",
        "\"", "\u{0080}", "\":\"Control\",",
        "\"", "\u{00f6}", "\":\"Latin Small Letter O With Diaeresis\",",
        "\"€\":\"Euro Sign\",\"😀\":\"Emoji: Grinning Face\",",
        "\"דּ\":\"Hebrew Letter Dalet With Dagesh\"}"
    );

    assert_eq!(canonical(input), expected.as_bytes());
}

#[test]
fn c1_recursive_object_and_array_order_is_preserved() {
    let input = r#"
    {
      "z": [{"b": 2, "a": 1}, {"d": {"y": 2, "x": 1}}],
      "a": [],
      "m": {}
    }
    "#;

    let expected = r#"{"a":[],"m":{},"z":[{"a":1,"b":2},{"d":{"x":1,"y":2}}]}"#;
    assert_eq!(canonical(input), expected.as_bytes());
}

#[test]
fn c1_whitespace_is_not_emitted() {
    let input = " { \n \"b\" : [ true, null, false ] , \"a\" : 1 } ";
    let expected = r#"{"a":1,"b":[true,null,false]}"#;
    assert_eq!(canonical(input), expected.as_bytes());
}

#[test]
fn c1_rfc_appendix_b_number_serialization_samples() {
    let cases = [
        ("0", "0"),
        ("-0.0", "0"),
        ("5e-324", "5e-324"),
        ("-5e-324", "-5e-324"),
        ("1.7976931348623157e+308", "1.7976931348623157e+308"),
        ("-1.7976931348623157e+308", "-1.7976931348623157e+308"),
        ("9007199254740992", "9007199254740992"),
        ("-9007199254740992", "-9007199254740992"),
        ("295147905179352830000", "295147905179352830000"),
        ("9.999999999999997e+22", "9.999999999999997e+22"),
        ("1e+23", "1e+23"),
        ("1.0000000000000001e+23", "1.0000000000000001e+23"),
        ("999999999999999700000", "999999999999999700000"),
        ("999999999999999900000", "999999999999999900000"),
        ("1e+21", "1e+21"),
        ("9.999999999999997e-7", "9.999999999999997e-7"),
        ("0.000001", "0.000001"),
        ("333333333.3333332", "333333333.3333332"),
        ("333333333.33333325", "333333333.33333325"),
        ("333333333.3333333", "333333333.3333333"),
        ("333333333.3333334", "333333333.3333334"),
        ("333333333.33333343", "333333333.33333343"),
        ("-0.0000033333333333333333", "-0.0000033333333333333333"),
        ("1424953923781206.25", "1424953923781206.2"),
    ];

    for (input_number, expected_number) in cases {
        let input = format!(r#"{{"n":{input_number}}}"#);
        let expected = format!(r#"{{"n":{expected_number}}}"#);
        assert_eq!(
            canonical(&input),
            expected.as_bytes(),
            "RFC 8785 Appendix B number mismatch for {input_number}"
        );
    }
}

#[test]
fn c1_utf8_is_exactly_the_canonical_output_encoding() {
    let input = r#"{"text":"€ / 😀 / דּ / å / 中文"}"#;
    let bytes = canonical(input);

    assert!(std::str::from_utf8(&bytes).is_ok(), "JCS output must be UTF-8");
    assert_eq!(
        bytes,
        r#"{"text":"€ / 😀 / דּ / å / 中文"}"#.as_bytes()
    );
}

#[test]
fn c1_i_json_duplicate_property_is_rejected_as_input_precondition() {
    // RFC 8785 §3.1 requires duplicate object property names to be rejected
    // by the I-JSON input validation step. The current `jcs.rs` surface accepts
    // an already-materialized `serde_json::Value`, so duplicate-name rejection
    // is explicitly an upstream parsing precondition, not a responsibility of
    // the serializer itself. This test records that boundary without silently
    // claiming the Value API performs duplicate detection.
    let duplicate_json = r#"{"a":1,"a":2}"#;
    let parsed: Value = serde_json::from_str(duplicate_json)
        .expect("serde_json can materialize a Value even when input names repeat");

    assert_eq!(parsed["a"], 2);
    assert_eq!(canonical(duplicate_json), br#"{"a":2}"#);
}

#[test]
fn c1_boundary_nonfinite_numbers_are_not_json_values() {
    assert!(serde_json::from_str::<Value>(r#"{"n":NaN}"#).is_err());
    assert!(serde_json::from_str::<Value>(r#"{"n":Infinity}"#).is_err());
    assert!(serde_json::from_str::<Value>(r#"{"n":-Infinity}"#).is_err());
}
