//! RFC 8785 (JCS) canonical serialization.
//!
//! # Responsibility
//!
//! Exactly one transformation, and nothing else:
//!
//! ```text
//! serde_json::Value  ->  RFC 8785 JCS  ->  Vec<u8>
//! ```
//!
//! # Provenance
//!
//! This module is a **mechanical extraction** of the conformance surface
//! previously located at `conformance/canonical/jcs.rs`, promoted into `src/`
//! so the production pipeline can reach it. The function body is unchanged:
//! the same call, to the same pinned engine, with the same signature.
//! `conformance/canonical/jcs.rs` is now a re-export of this module, so
//! CANONICAL-001 and the C1 corpus execute against **this** code — their
//! passing results are therefore evidence about the production surface, not
//! about a parallel copy.
//!
//! # Verification status
//!
//! C1 (`conformance/canonical/c1_full_domain_jcs.rs`) verifies this function
//! against RFC 8785 §3.2.1–§3.2.4 and the Appendix B numeric corpus, with
//! expected vectors frozen from the RFC rather than generated by the engine.
//!
//! # Scope
//!
//! Canonicalization only. This module does **not** validate its input: RFC 8785
//! §3.1 places I-JSON input validation (well-formedness, UTF-8, duplicate
//! member-name rejection) in a separate upstream stage. That stage is
//! [`crate::event_payload`]. Do not add duplicate detection here — by the time a
//! [`serde_json::Value`] exists, duplicate member names are already gone.
//!
//! This module computes no hash and defines no hash domain. Merkle domain
//! separation (`0x00` / `0x01`) lives in [`crate::merkle`] and is untouched.
//!
//! # Engine
//!
//! [`serde_json_canonicalizer`] (pinned `=0.3.2`, MIT). Plain
//! `serde_json::to_vec` / `serde_json::to_string` are deliberately **not**
//! used as canonical serializers: they emit insertion/BTree order with
//! serde_json's own number formatting, which is not the RFC 8785 contract.

/// Serialize `value` to RFC 8785 canonical UTF-8 bytes.
///
/// Key ordering, number formatting, and string escaping are decided by the
/// JCS engine — the caller supplies no ordering hints and performs no
/// pre-normalization.
///
/// # Errors
///
/// Returns the underlying [`serde_json::Error`] if the value cannot be
/// canonically serialized (e.g. non-string map keys, or a non-finite number).
pub fn canonical_bytes(value: &serde_json::Value) -> Result<Vec<u8>, serde_json::Error> {
    serde_json_canonicalizer::to_vec(value)
}
